theme: jekyll-theme-cayman
title: Animal Kingdom Classification - ABE 516X Course Project
description: The goal of this project is to create a machine learning model to classify animals to their kingdom based on an image.
