theme: jekyll-theme-cayman
title: Animal Group Classification <br/> ABE 516X Course Project <br/> Fall 2019
description: Creating and evaluating a machine learning model to classify animals to their respective group based on an input image.
