theme: jekyll-theme-cayman
title: Animal Group Classification
ABE 516X Course Project
Fall 2019
description: Creating and evaluating a machine learning model to classify animals to their respective group based on an input image.
